spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gtb_final?serverTimezone=Asia/Shanghai&useunicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
